create table Horse(
horse_id INTEGER GENERATED BY DEFAULT AS IDENTITY Primary Key,
horse_name varchar(100),
horse_photo varchar(200),
horse_priceperhour float,
horse_therapytype varchar(100),
horse_race varchar(100),
horse_deleted boolean
);

create table Invoice(
invoice_id INTEGER GENERATED BY DEFAULT AS IDENTITY Primary Key,
invoice_date date,
invoice_clientfname varchar(60),
invoice_clientsname varchar(80),
invoice_address varchar(100),
invoice_postcode varchar(10),
invoice_place varchar(100),
invoice_sum float
);

create table Therapy(
therapy_id integer,
horse integer Foreign key references Horse(horse_id),
invoice integer Foreign key references Invoice(invoice_id),
therapy_hour float,
therapy_price float,
therapy_type varchar(100),
Primary key(therapy_id, horse, invoice)
);


